### ISSUE TITLE
say command kills my Logitech Harmony-Action

### ISSUE THREAD

**Issue by Effendi68** [chrisns/docker-node-sonos-http-api#10]
Say works fine for me by http-request but if I use say on my Sonos-Playbar when a Logitech Harmony Action is running (for example watching TV) the say-action kills my Harmony-Action. 

When the voice output is finished, the Logitech action is also canceled and the TV is turned off.
The problem only occurs with an output on the Playbar.
I can not see any connection and I'm a bit clueless.

The control of the Sonos devices works flawlessly, as well as the voice output. However, I have this error message in the logfile when starting the Docker module: "WARN Could not read file /app/settings.json, ignoring."

I hope, someone can help me.

**Comment by chrisns** [comment]
Hi, I do happen to have a playbar, and harmony, but can't reproduce what you're describing in my config.
my harmony fire+forget action and doesn't watch what the speakers or tv do after it has sent its commands.
No idea how to really help you beyond that since its a query more related to the harmony, I imagine you'd get similar results by using the sonos app to play some music?
